/**
 * 
 */
package com.ps.coding.domainassessment.controller;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.Mockito;
import org.mockito.MockitoAnnotations;
import org.mockito.junit.MockitoJUnitRunner;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.ResultMatcher;
import org.springframework.test.web.servlet.request.MockHttpServletRequestBuilder;
import org.springframework.test.web.servlet.request.MockMvcRequestBuilders;
import org.springframework.test.web.servlet.result.MockMvcResultHandlers;
import org.springframework.test.web.servlet.result.MockMvcResultMatchers;
import org.springframework.test.web.servlet.setup.MockMvcBuilders;

import com.ps.coding.domainassessment.service.TeamStandingService;

/**
 * @author aswini.nellimarla
 *
 */
@RunWith(MockitoJUnitRunner.Silent.class)
public class TeamStandingControllerTest {

	@InjectMocks
	private TeamStandingController controller;

	@Mock
	private TeamStandingService service;

	private MockMvc mockMvc;

	private String response = "[\r\n" + "  {\r\n" + "    \"country_name\": \"England\",\r\n"
			+ "    \"league_id\": \"148\",\r\n" + "    \"league_name\": \"Premier League\",\r\n"
			+ "    \"team_id\": \"2621\",\r\n" + "    \"team_name\": \"Liverpool\",\r\n"
			+ "    \"overall_promotion\": \"Promotion - Champions League (Group Stage)\",\r\n"
			+ "    \"overall_league_position\": \"1\",\r\n" + "    \"overall_league_payed\": \"29\",\r\n"
			+ "    \"overall_league_W\": \"27\",\r\n" + "    \"overall_league_D\": \"1\",\r\n"
			+ "    \"overall_league_L\": \"1\",\r\n" + "    \"overall_league_GF\": \"66\",\r\n"
			+ "    \"overall_league_GA\": \"21\",\r\n" + "    \"overall_league_PTS\": \"82\",\r\n"
			+ "    \"home_league_position\": \"1\",\r\n" + "    \"home_promotion\": \"\",\r\n"
			+ "    \"home_league_payed\": \"15\",\r\n" + "    \"home_league_W\": \"15\",\r\n"
			+ "    \"home_league_D\": \"0\",\r\n" + "    \"home_league_L\": \"0\",\r\n"
			+ "    \"home_league_GF\": \"40\",\r\n" + "    \"home_league_GA\": \"12\",\r\n"
			+ "    \"home_league_PTS\": \"45\",\r\n" + "    \"away_league_position\": \"1\",\r\n"
			+ "    \"away_promotion\": \"\",\r\n" + "    \"away_league_payed\": \"14\",\r\n"
			+ "    \"away_league_W\": \"12\",\r\n" + "    \"away_league_D\": \"1\",\r\n"
			+ "    \"away_league_L\": \"1\",\r\n" + "    \"away_league_GF\": \"26\",\r\n"
			+ "    \"away_league_GA\": \"9\",\r\n" + "    \"away_league_PTS\": \"37\",\r\n"
			+ "    \"league_round\": \"\",\r\n"
			+ "    \"team_badge\": \"https:\\/\\/apiv2.apifootball.com\\/badges\\/2621_liverpool.png\"\r\n" + "  },\r\n"
			+ "  {\r\n" + "    \"country_name\": \"England\",\r\n" + "    \"league_id\": \"148\",\r\n"
			+ "    \"league_name\": \"Premier League\",\r\n" + "    \"team_id\": \"2626\",\r\n"
			+ "    \"team_name\": \"Manchester City\",\r\n"
			+ "    \"overall_promotion\": \"Promotion - Champions League (Group Stage)\",\r\n"
			+ "    \"overall_league_position\": \"2\",\r\n" + "    \"overall_league_payed\": \"28\",\r\n"
			+ "    \"overall_league_W\": \"18\",\r\n" + "    \"overall_league_D\": \"3\",\r\n"
			+ "    \"overall_league_L\": \"7\",\r\n" + "    \"overall_league_GF\": \"68\",\r\n"
			+ "    \"overall_league_GA\": \"31\",\r\n" + "    \"overall_league_PTS\": \"57\",\r\n"
			+ "    \"home_league_position\": \"3\",\r\n" + "    \"home_promotion\": \"\",\r\n"
			+ "    \"home_league_payed\": \"13\",\r\n" + "    \"home_league_W\": \"9\",\r\n"
			+ "    \"home_league_D\": \"2\",\r\n" + "    \"home_league_L\": \"2\",\r\n"
			+ "    \"home_league_GF\": \"33\",\r\n" + "    \"home_league_GA\": \"12\",\r\n"
			+ "    \"home_league_PTS\": \"29\",\r\n" + "    \"away_league_position\": \"2\",\r\n"
			+ "    \"away_promotion\": \"\",\r\n" + "    \"away_league_payed\": \"15\",\r\n"
			+ "    \"away_league_W\": \"9\",\r\n" + "    \"away_league_D\": \"1\",\r\n"
			+ "    \"away_league_L\": \"5\",\r\n" + "    \"away_league_GF\": \"35\",\r\n"
			+ "    \"away_league_GA\": \"19\",\r\n" + "    \"away_league_PTS\": \"28\",\r\n"
			+ "    \"league_round\": \"\",\r\n"
			+ "    \"team_badge\": \"https:\\/\\/apiv2.apifootball.com\\/badges\\/2626_manchester-city.png\"\r\n"
			+ "  },\r\n" + "  {\r\n" + "    \"country_name\": \"England\",\r\n" + "    \"league_id\": \"148\",\r\n"
			+ "    \"league_name\": \"Premier League\",\r\n" + "    \"team_id\": \"2611\",\r\n"
			+ "    \"team_name\": \"Leicester\",\r\n"
			+ "    \"overall_promotion\": \"Promotion - Champions League (Group Stage)\",\r\n"
			+ "    \"overall_league_position\": \"3\",\r\n" + "    \"overall_league_payed\": \"29\",\r\n"
			+ "    \"overall_league_W\": \"16\",\r\n" + "    \"overall_league_D\": \"5\",\r\n"
			+ "    \"overall_league_L\": \"8\",\r\n" + "    \"overall_league_GF\": \"58\",\r\n"
			+ "    \"overall_league_GA\": \"28\",\r\n" + "    \"overall_league_PTS\": \"53\",\r\n"
			+ "    \"home_league_position\": \"2\",\r\n" + "    \"home_promotion\": \"\",\r\n"
			+ "    \"home_league_payed\": \"15\",\r\n" + "    \"home_league_W\": \"9\",\r\n"
			+ "    \"home_league_D\": \"3\",\r\n" + "    \"home_league_L\": \"3\",\r\n"
			+ "    \"home_league_GF\": \"30\",\r\n" + "    \"home_league_GA\": \"15\",\r\n"
			+ "    \"home_league_PTS\": \"30\",\r\n" + "    \"away_league_position\": \"4\",\r\n"
			+ "    \"away_promotion\": \"\",\r\n" + "    \"away_league_payed\": \"14\",\r\n"
			+ "    \"away_league_W\": \"7\",\r\n" + "    \"away_league_D\": \"2\",\r\n"
			+ "    \"away_league_L\": \"5\",\r\n" + "    \"away_league_GF\": \"28\",\r\n"
			+ "    \"away_league_GA\": \"13\",\r\n" + "    \"away_league_PTS\": \"23\",\r\n"
			+ "    \"league_round\": \"\",\r\n"
			+ "    \"team_badge\": \"https:\\/\\/apiv2.apifootball.com\\/badges\\/2611_leicester.png\"\r\n" + "  },\r\n"
			+ "  {\r\n" + "    \"country_name\": \"England\",\r\n" + "    \"league_id\": \"148\",\r\n"
			+ "    \"league_name\": \"Premier League\",\r\n" + "    \"team_id\": \"2616\",\r\n"
			+ "    \"team_name\": \"Chelsea\",\r\n"
			+ "    \"overall_promotion\": \"Promotion - Champions League (Group Stage)\",\r\n"
			+ "    \"overall_league_position\": \"4\",\r\n" + "    \"overall_league_payed\": \"29\",\r\n"
			+ "    \"overall_league_W\": \"14\",\r\n" + "    \"overall_league_D\": \"6\",\r\n"
			+ "    \"overall_league_L\": \"9\",\r\n" + "    \"overall_league_GF\": \"51\",\r\n"
			+ "    \"overall_league_GA\": \"39\",\r\n" + "    \"overall_league_PTS\": \"48\",\r\n"
			+ "    \"home_league_position\": \"8\",\r\n" + "    \"home_promotion\": \"\",\r\n"
			+ "    \"home_league_payed\": \"15\",\r\n" + "    \"home_league_W\": \"7\",\r\n"
			+ "    \"home_league_D\": \"3\",\r\n" + "    \"home_league_L\": \"5\",\r\n"
			+ "    \"home_league_GF\": \"22\",\r\n" + "    \"home_league_GA\": \"15\",\r\n"
			+ "    \"home_league_PTS\": \"24\",\r\n" + "    \"away_league_position\": \"3\",\r\n"
			+ "    \"away_promotion\": \"\",\r\n" + "    \"away_league_payed\": \"14\",\r\n"
			+ "    \"away_league_W\": \"7\",\r\n" + "    \"away_league_D\": \"3\",\r\n"
			+ "    \"away_league_L\": \"4\",\r\n" + "    \"away_league_GF\": \"29\",\r\n"
			+ "    \"away_league_GA\": \"24\",\r\n" + "    \"away_league_PTS\": \"24\",\r\n"
			+ "    \"league_round\": \"\",\r\n"
			+ "    \"team_badge\": \"https:\\/\\/apiv2.apifootball.com\\/badges\\/2616_chelsea.png\"\r\n" + "  },\r\n"
			+ "  {\r\n" + "    \"country_name\": \"England\",\r\n" + "    \"league_id\": \"148\",\r\n"
			+ "    \"league_name\": \"Premier League\",\r\n" + "    \"team_id\": \"2627\",\r\n"
			+ "    \"team_name\": \"Manchester Utd\",\r\n"
			+ "    \"overall_promotion\": \"Promotion - Europa League (Group Stage)\",\r\n"
			+ "    \"overall_league_position\": \"5\",\r\n" + "    \"overall_league_payed\": \"29\",\r\n"
			+ "    \"overall_league_W\": \"12\",\r\n" + "    \"overall_league_D\": \"9\",\r\n"
			+ "    \"overall_league_L\": \"8\",\r\n" + "    \"overall_league_GF\": \"44\",\r\n"
			+ "    \"overall_league_GA\": \"30\",\r\n" + "    \"overall_league_PTS\": \"45\",\r\n"
			+ "    \"home_league_position\": \"4\",\r\n" + "    \"home_promotion\": \"\",\r\n"
			+ "    \"home_league_payed\": \"15\",\r\n" + "    \"home_league_W\": \"8\",\r\n"
			+ "    \"home_league_D\": \"5\",\r\n" + "    \"home_league_L\": \"2\",\r\n"
			+ "    \"home_league_GF\": \"29\",\r\n" + "    \"home_league_GA\": \"12\",\r\n"
			+ "    \"home_league_PTS\": \"29\",\r\n" + "    \"away_league_position\": \"9\",\r\n"
			+ "    \"away_promotion\": \"\",\r\n" + "    \"away_league_payed\": \"14\",\r\n"
			+ "    \"away_league_W\": \"4\",\r\n" + "    \"away_league_D\": \"4\",\r\n"
			+ "    \"away_league_L\": \"6\",\r\n" + "    \"away_league_GF\": \"15\",\r\n"
			+ "    \"away_league_GA\": \"18\",\r\n" + "    \"away_league_PTS\": \"16\",\r\n"
			+ "    \"league_round\": \"\",\r\n"
			+ "    \"team_badge\": \"https:\\/\\/apiv2.apifootball.com\\/badges\\/2627_manchester-united.png\"\r\n"
			+ "  },\r\n" + "  {\r\n" + "    \"country_name\": \"England\",\r\n" + "    \"league_id\": \"148\",\r\n"
			+ "    \"league_name\": \"Premier League\",\r\n" + "    \"team_id\": \"2646\",\r\n"
			+ "    \"team_name\": \"Wolves\",\r\n" + "    \"overall_promotion\": \"\",\r\n"
			+ "    \"overall_league_position\": \"6\",\r\n" + "    \"overall_league_payed\": \"29\",\r\n"
			+ "    \"overall_league_W\": \"10\",\r\n" + "    \"overall_league_D\": \"13\",\r\n"
			+ "    \"overall_league_L\": \"6\",\r\n" + "    \"overall_league_GF\": \"41\",\r\n"
			+ "    \"overall_league_GA\": \"34\",\r\n" + "    \"overall_league_PTS\": \"43\",\r\n"
			+ "    \"home_league_position\": \"11\",\r\n" + "    \"home_promotion\": \"\",\r\n"
			+ "    \"home_league_payed\": \"15\",\r\n" + "    \"home_league_W\": \"5\",\r\n"
			+ "    \"home_league_D\": \"7\",\r\n" + "    \"home_league_L\": \"3\",\r\n"
			+ "    \"home_league_GF\": \"21\",\r\n" + "    \"home_league_GA\": \"17\",\r\n"
			+ "    \"home_league_PTS\": \"22\",\r\n" + "    \"away_league_position\": \"5\",\r\n"
			+ "    \"away_promotion\": \"\",\r\n" + "    \"away_league_payed\": \"14\",\r\n"
			+ "    \"away_league_W\": \"5\",\r\n" + "    \"away_league_D\": \"6\",\r\n"
			+ "    \"away_league_L\": \"3\",\r\n" + "    \"away_league_GF\": \"20\",\r\n"
			+ "    \"away_league_GA\": \"17\",\r\n" + "    \"away_league_PTS\": \"21\",\r\n"
			+ "    \"league_round\": \"\",\r\n"
			+ "    \"team_badge\": \"https:\\/\\/apiv2.apifootball.com\\/badges\\/2646_wolves.png\"\r\n" + "  },\r\n"
			+ "  {\r\n" + "    \"country_name\": \"England\",\r\n" + "    \"league_id\": \"148\",\r\n"
			+ "    \"league_name\": \"Premier League\",\r\n" + "    \"team_id\": \"2654\",\r\n"
			+ "    \"team_name\": \"Sheffield Utd\",\r\n" + "    \"overall_promotion\": \"\",\r\n"
			+ "    \"overall_league_position\": \"7\",\r\n" + "    \"overall_league_payed\": \"28\",\r\n"
			+ "    \"overall_league_W\": \"11\",\r\n" + "    \"overall_league_D\": \"10\",\r\n"
			+ "    \"overall_league_L\": \"7\",\r\n" + "    \"overall_league_GF\": \"30\",\r\n"
			+ "    \"overall_league_GA\": \"25\",\r\n" + "    \"overall_league_PTS\": \"43\",\r\n"
			+ "    \"home_league_position\": \"9\",\r\n" + "    \"home_promotion\": \"\",\r\n"
			+ "    \"home_league_payed\": \"15\",\r\n" + "    \"home_league_W\": \"7\",\r\n"
			+ "    \"home_league_D\": \"3\",\r\n" + "    \"home_league_L\": \"5\",\r\n"
			+ "    \"home_league_GF\": \"17\",\r\n" + "    \"home_league_GA\": \"13\",\r\n"
			+ "    \"home_league_PTS\": \"24\",\r\n" + "    \"away_league_position\": \"7\",\r\n"
			+ "    \"away_promotion\": \"\",\r\n" + "    \"away_league_payed\": \"13\",\r\n"
			+ "    \"away_league_W\": \"4\",\r\n" + "    \"away_league_D\": \"7\",\r\n"
			+ "    \"away_league_L\": \"2\",\r\n" + "    \"away_league_GF\": \"13\",\r\n"
			+ "    \"away_league_GA\": \"12\",\r\n" + "    \"away_league_PTS\": \"19\",\r\n"
			+ "    \"league_round\": \"\",\r\n"
			+ "    \"team_badge\": \"https:\\/\\/apiv2.apifootball.com\\/badges\\/2654_sheffield-utd.png\"\r\n"
			+ "  },\r\n" + "  {\r\n" + "    \"country_name\": \"England\",\r\n" + "    \"league_id\": \"148\",\r\n"
			+ "    \"league_name\": \"Premier League\",\r\n" + "    \"team_id\": \"2628\",\r\n"
			+ "    \"team_name\": \"Tottenham\",\r\n" + "    \"overall_promotion\": \"\",\r\n"
			+ "    \"overall_league_position\": \"8\",\r\n" + "    \"overall_league_payed\": \"29\",\r\n"
			+ "    \"overall_league_W\": \"11\",\r\n" + "    \"overall_league_D\": \"8\",\r\n"
			+ "    \"overall_league_L\": \"10\",\r\n" + "    \"overall_league_GF\": \"47\",\r\n"
			+ "    \"overall_league_GA\": \"40\",\r\n" + "    \"overall_league_PTS\": \"41\",\r\n"
			+ "    \"home_league_position\": \"5\",\r\n" + "    \"home_promotion\": \"\",\r\n"
			+ "    \"home_league_payed\": \"14\",\r\n" + "    \"home_league_W\": \"8\",\r\n"
			+ "    \"home_league_D\": \"2\",\r\n" + "    \"home_league_L\": \"4\",\r\n"
			+ "    \"home_league_GF\": \"27\",\r\n" + "    \"home_league_GA\": \"15\",\r\n"
			+ "    \"home_league_PTS\": \"26\",\r\n" + "    \"away_league_position\": \"11\",\r\n"
			+ "    \"away_promotion\": \"\",\r\n" + "    \"away_league_payed\": \"15\",\r\n"
			+ "    \"away_league_W\": \"3\",\r\n" + "    \"away_league_D\": \"6\",\r\n"
			+ "    \"away_league_L\": \"6\",\r\n" + "    \"away_league_GF\": \"20\",\r\n"
			+ "    \"away_league_GA\": \"25\",\r\n" + "    \"away_league_PTS\": \"15\",\r\n"
			+ "    \"league_round\": \"\",\r\n"
			+ "    \"team_badge\": \"https:\\/\\/apiv2.apifootball.com\\/badges\\/2628_tottenham.png\"\r\n" + "  },\r\n"
			+ "  {\r\n" + "    \"country_name\": \"England\",\r\n" + "    \"league_id\": \"148\",\r\n"
			+ "    \"league_name\": \"Premier League\",\r\n" + "    \"team_id\": \"2617\",\r\n"
			+ "    \"team_name\": \"Arsenal\",\r\n" + "    \"overall_promotion\": \"\",\r\n"
			+ "    \"overall_league_position\": \"9\",\r\n" + "    \"overall_league_payed\": \"28\",\r\n"
			+ "    \"overall_league_W\": \"9\",\r\n" + "    \"overall_league_D\": \"13\",\r\n"
			+ "    \"overall_league_L\": \"6\",\r\n" + "    \"overall_league_GF\": \"40\",\r\n"
			+ "    \"overall_league_GA\": \"36\",\r\n" + "    \"overall_league_PTS\": \"40\",\r\n"
			+ "    \"home_league_position\": \"6\",\r\n" + "    \"home_promotion\": \"\",\r\n"
			+ "    \"home_league_payed\": \"15\",\r\n" + "    \"home_league_W\": \"7\",\r\n"
			+ "    \"home_league_D\": \"5\",\r\n" + "    \"home_league_L\": \"3\",\r\n"
			+ "    \"home_league_GF\": \"26\",\r\n" + "    \"home_league_GA\": \"20\",\r\n"
			+ "    \"home_league_PTS\": \"26\",\r\n" + "    \"away_league_position\": \"12\",\r\n"
			+ "    \"away_promotion\": \"\",\r\n" + "    \"away_league_payed\": \"13\",\r\n"
			+ "    \"away_league_W\": \"2\",\r\n" + "    \"away_league_D\": \"8\",\r\n"
			+ "    \"away_league_L\": \"3\",\r\n" + "    \"away_league_GF\": \"14\",\r\n"
			+ "    \"away_league_GA\": \"16\",\r\n" + "    \"away_league_PTS\": \"14\",\r\n"
			+ "    \"league_round\": \"\",\r\n"
			+ "    \"team_badge\": \"https:\\/\\/apiv2.apifootball.com\\/badges\\/2617_arsenal.png\"\r\n" + "  },\r\n"
			+ "  {\r\n" + "    \"country_name\": \"England\",\r\n" + "    \"league_id\": \"148\",\r\n"
			+ "    \"league_name\": \"Premier League\",\r\n" + "    \"team_id\": \"2629\",\r\n"
			+ "    \"team_name\": \"Burnley\",\r\n" + "    \"overall_promotion\": \"\",\r\n"
			+ "    \"overall_league_position\": \"10\",\r\n" + "    \"overall_league_payed\": \"29\",\r\n"
			+ "    \"overall_league_W\": \"11\",\r\n" + "    \"overall_league_D\": \"6\",\r\n"
			+ "    \"overall_league_L\": \"12\",\r\n" + "    \"overall_league_GF\": \"34\",\r\n"
			+ "    \"overall_league_GA\": \"40\",\r\n" + "    \"overall_league_PTS\": \"39\",\r\n"
			+ "    \"home_league_position\": \"10\",\r\n" + "    \"home_promotion\": \"\",\r\n"
			+ "    \"home_league_payed\": \"15\",\r\n" + "    \"home_league_W\": \"7\",\r\n"
			+ "    \"home_league_D\": \"2\",\r\n" + "    \"home_league_L\": \"6\",\r\n"
			+ "    \"home_league_GF\": \"20\",\r\n" + "    \"home_league_GA\": \"19\",\r\n"
			+ "    \"home_league_PTS\": \"23\",\r\n" + "    \"away_league_position\": \"10\",\r\n"
			+ "    \"away_promotion\": \"\",\r\n" + "    \"away_league_payed\": \"14\",\r\n"
			+ "    \"away_league_W\": \"4\",\r\n" + "    \"away_league_D\": \"4\",\r\n"
			+ "    \"away_league_L\": \"6\",\r\n" + "    \"away_league_GF\": \"14\",\r\n"
			+ "    \"away_league_GA\": \"21\",\r\n" + "    \"away_league_PTS\": \"16\",\r\n"
			+ "    \"league_round\": \"\",\r\n"
			+ "    \"team_badge\": \"https:\\/\\/apiv2.apifootball.com\\/badges\\/2629_burnley.png\"\r\n" + "  },\r\n"
			+ "  {\r\n" + "    \"country_name\": \"England\",\r\n" + "    \"league_id\": \"148\",\r\n"
			+ "    \"league_name\": \"Premier League\",\r\n" + "    \"team_id\": \"2619\",\r\n"
			+ "    \"team_name\": \"Crystal Palace\",\r\n" + "    \"overall_promotion\": \"\",\r\n"
			+ "    \"overall_league_position\": \"11\",\r\n" + "    \"overall_league_payed\": \"29\",\r\n"
			+ "    \"overall_league_W\": \"10\",\r\n" + "    \"overall_league_D\": \"9\",\r\n"
			+ "    \"overall_league_L\": \"10\",\r\n" + "    \"overall_league_GF\": \"26\",\r\n"
			+ "    \"overall_league_GA\": \"32\",\r\n" + "    \"overall_league_PTS\": \"39\",\r\n"
			+ "    \"home_league_position\": \"12\",\r\n" + "    \"home_promotion\": \"\",\r\n"
			+ "    \"home_league_payed\": \"15\",\r\n" + "    \"home_league_W\": \"6\",\r\n"
			+ "    \"home_league_D\": \"4\",\r\n" + "    \"home_league_L\": \"5\",\r\n"
			+ "    \"home_league_GF\": \"12\",\r\n" + "    \"home_league_GA\": \"13\",\r\n"
			+ "    \"home_league_PTS\": \"22\",\r\n" + "    \"away_league_position\": \"8\",\r\n"
			+ "    \"away_promotion\": \"\",\r\n" + "    \"away_league_payed\": \"14\",\r\n"
			+ "    \"away_league_W\": \"4\",\r\n" + "    \"away_league_D\": \"5\",\r\n"
			+ "    \"away_league_L\": \"5\",\r\n" + "    \"away_league_GF\": \"14\",\r\n"
			+ "    \"away_league_GA\": \"19\",\r\n" + "    \"away_league_PTS\": \"17\",\r\n"
			+ "    \"league_round\": \"\",\r\n"
			+ "    \"team_badge\": \"https:\\/\\/apiv2.apifootball.com\\/badges\\/2619_crystal-palace.png\"\r\n"
			+ "  },\r\n" + "  {\r\n" + "    \"country_name\": \"England\",\r\n" + "    \"league_id\": \"148\",\r\n"
			+ "    \"league_name\": \"Premier League\",\r\n" + "    \"team_id\": \"2612\",\r\n"
			+ "    \"team_name\": \"Everton\",\r\n" + "    \"overall_promotion\": \"\",\r\n"
			+ "    \"overall_league_position\": \"12\",\r\n" + "    \"overall_league_payed\": \"29\",\r\n"
			+ "    \"overall_league_W\": \"10\",\r\n" + "    \"overall_league_D\": \"7\",\r\n"
			+ "    \"overall_league_L\": \"12\",\r\n" + "    \"overall_league_GF\": \"37\",\r\n"
			+ "    \"overall_league_GA\": \"46\",\r\n" + "    \"overall_league_PTS\": \"37\",\r\n"
			+ "    \"home_league_position\": \"7\",\r\n" + "    \"home_promotion\": \"\",\r\n"
			+ "    \"home_league_payed\": \"14\",\r\n" + "    \"home_league_W\": \"7\",\r\n"
			+ "    \"home_league_D\": \"4\",\r\n" + "    \"home_league_L\": \"3\",\r\n"
			+ "    \"home_league_GF\": \"19\",\r\n" + "    \"home_league_GA\": \"15\",\r\n"
			+ "    \"home_league_PTS\": \"25\",\r\n" + "    \"away_league_position\": \"15\",\r\n"
			+ "    \"away_promotion\": \"\",\r\n" + "    \"away_league_payed\": \"15\",\r\n"
			+ "    \"away_league_W\": \"3\",\r\n" + "    \"away_league_D\": \"3\",\r\n"
			+ "    \"away_league_L\": \"9\",\r\n" + "    \"away_league_GF\": \"18\",\r\n"
			+ "    \"away_league_GA\": \"31\",\r\n" + "    \"away_league_PTS\": \"12\",\r\n"
			+ "    \"league_round\": \"\",\r\n"
			+ "    \"team_badge\": \"https:\\/\\/apiv2.apifootball.com\\/badges\\/2612_everton.png\"\r\n" + "  },\r\n"
			+ "  {\r\n" + "    \"country_name\": \"England\",\r\n" + "    \"league_id\": \"148\",\r\n"
			+ "    \"league_name\": \"Premier League\",\r\n" + "    \"team_id\": \"2630\",\r\n"
			+ "    \"team_name\": \"Newcastle\",\r\n" + "    \"overall_promotion\": \"\",\r\n"
			+ "    \"overall_league_position\": \"13\",\r\n" + "    \"overall_league_payed\": \"29\",\r\n"
			+ "    \"overall_league_W\": \"9\",\r\n" + "    \"overall_league_D\": \"8\",\r\n"
			+ "    \"overall_league_L\": \"12\",\r\n" + "    \"overall_league_GF\": \"25\",\r\n"
			+ "    \"overall_league_GA\": \"41\",\r\n" + "    \"overall_league_PTS\": \"35\",\r\n"
			+ "    \"home_league_position\": \"13\",\r\n" + "    \"home_promotion\": \"\",\r\n"
			+ "    \"home_league_payed\": \"14\",\r\n" + "    \"home_league_W\": \"5\",\r\n"
			+ "    \"home_league_D\": \"6\",\r\n" + "    \"home_league_L\": \"3\",\r\n"
			+ "    \"home_league_GF\": \"12\",\r\n" + "    \"home_league_GA\": \"12\",\r\n"
			+ "    \"home_league_PTS\": \"21\",\r\n" + "    \"away_league_position\": \"13\",\r\n"
			+ "    \"away_promotion\": \"\",\r\n" + "    \"away_league_payed\": \"15\",\r\n"
			+ "    \"away_league_W\": \"4\",\r\n" + "    \"away_league_D\": \"2\",\r\n"
			+ "    \"away_league_L\": \"9\",\r\n" + "    \"away_league_GF\": \"13\",\r\n"
			+ "    \"away_league_GA\": \"29\",\r\n" + "    \"away_league_PTS\": \"14\",\r\n"
			+ "    \"league_round\": \"\",\r\n"
			+ "    \"team_badge\": \"https:\\/\\/apiv2.apifootball.com\\/badges\\/2630_newcastle.png\"\r\n" + "  },\r\n"
			+ "  {\r\n" + "    \"country_name\": \"England\",\r\n" + "    \"league_id\": \"148\",\r\n"
			+ "    \"league_name\": \"Premier League\",\r\n" + "    \"team_id\": \"2614\",\r\n"
			+ "    \"team_name\": \"Southampton\",\r\n" + "    \"overall_promotion\": \"\",\r\n"
			+ "    \"overall_league_position\": \"14\",\r\n" + "    \"overall_league_payed\": \"29\",\r\n"
			+ "    \"overall_league_W\": \"10\",\r\n" + "    \"overall_league_D\": \"4\",\r\n"
			+ "    \"overall_league_L\": \"15\",\r\n" + "    \"overall_league_GF\": \"35\",\r\n"
			+ "    \"overall_league_GA\": \"52\",\r\n" + "    \"overall_league_PTS\": \"34\",\r\n"
			+ "    \"home_league_position\": \"20\",\r\n" + "    \"home_promotion\": \"\",\r\n"
			+ "    \"home_league_payed\": \"15\",\r\n" + "    \"home_league_W\": \"4\",\r\n"
			+ "    \"home_league_D\": \"2\",\r\n" + "    \"home_league_L\": \"9\",\r\n"
			+ "    \"home_league_GF\": \"16\",\r\n" + "    \"home_league_GA\": \"31\",\r\n"
			+ "    \"home_league_PTS\": \"14\",\r\n" + "    \"away_league_position\": \"6\",\r\n"
			+ "    \"away_promotion\": \"\",\r\n" + "    \"away_league_payed\": \"14\",\r\n"
			+ "    \"away_league_W\": \"6\",\r\n" + "    \"away_league_D\": \"2\",\r\n"
			+ "    \"away_league_L\": \"6\",\r\n" + "    \"away_league_GF\": \"19\",\r\n"
			+ "    \"away_league_GA\": \"21\",\r\n" + "    \"away_league_PTS\": \"20\",\r\n"
			+ "    \"league_round\": \"\",\r\n"
			+ "    \"team_badge\": \"https:\\/\\/apiv2.apifootball.com\\/badges\\/2614_southampton.png\"\r\n"
			+ "  },\r\n" + "  {\r\n" + "    \"country_name\": \"England\",\r\n" + "    \"league_id\": \"148\",\r\n"
			+ "    \"league_name\": \"Premier League\",\r\n" + "    \"team_id\": \"2613\",\r\n"
			+ "    \"team_name\": \"Brighton\",\r\n" + "    \"overall_promotion\": \"\",\r\n"
			+ "    \"overall_league_position\": \"15\",\r\n" + "    \"overall_league_payed\": \"29\",\r\n"
			+ "    \"overall_league_W\": \"6\",\r\n" + "    \"overall_league_D\": \"11\",\r\n"
			+ "    \"overall_league_L\": \"12\",\r\n" + "    \"overall_league_GF\": \"32\",\r\n"
			+ "    \"overall_league_GA\": \"40\",\r\n" + "    \"overall_league_PTS\": \"29\",\r\n"
			+ "    \"home_league_position\": \"14\",\r\n" + "    \"home_promotion\": \"\",\r\n"
			+ "    \"home_league_payed\": \"14\",\r\n" + "    \"home_league_W\": \"4\",\r\n"
			+ "    \"home_league_D\": \"6\",\r\n" + "    \"home_league_L\": \"4\",\r\n"
			+ "    \"home_league_GF\": \"17\",\r\n" + "    \"home_league_GA\": \"15\",\r\n"
			+ "    \"home_league_PTS\": \"18\",\r\n" + "    \"away_league_position\": \"16\",\r\n"
			+ "    \"away_promotion\": \"\",\r\n" + "    \"away_league_payed\": \"15\",\r\n"
			+ "    \"away_league_W\": \"2\",\r\n" + "    \"away_league_D\": \"5\",\r\n"
			+ "    \"away_league_L\": \"8\",\r\n" + "    \"away_league_GF\": \"15\",\r\n"
			+ "    \"away_league_GA\": \"25\",\r\n" + "    \"away_league_PTS\": \"11\",\r\n"
			+ "    \"league_round\": \"\",\r\n"
			+ "    \"team_badge\": \"https:\\/\\/apiv2.apifootball.com\\/badges\\/2613_brighton.png\"\r\n" + "  },\r\n"
			+ "  {\r\n" + "    \"country_name\": \"England\",\r\n" + "    \"league_id\": \"148\",\r\n"
			+ "    \"league_name\": \"Premier League\",\r\n" + "    \"team_id\": \"2620\",\r\n"
			+ "    \"team_name\": \"West Ham\",\r\n" + "    \"overall_promotion\": \"\",\r\n"
			+ "    \"overall_league_position\": \"16\",\r\n" + "    \"overall_league_payed\": \"29\",\r\n"
			+ "    \"overall_league_W\": \"7\",\r\n" + "    \"overall_league_D\": \"6\",\r\n"
			+ "    \"overall_league_L\": \"16\",\r\n" + "    \"overall_league_GF\": \"35\",\r\n"
			+ "    \"overall_league_GA\": \"50\",\r\n" + "    \"overall_league_PTS\": \"27\",\r\n"
			+ "    \"home_league_position\": \"18\",\r\n" + "    \"home_promotion\": \"\",\r\n"
			+ "    \"home_league_payed\": \"14\",\r\n" + "    \"home_league_W\": \"4\",\r\n"
			+ "    \"home_league_D\": \"3\",\r\n" + "    \"home_league_L\": \"7\",\r\n"
			+ "    \"home_league_GF\": \"23\",\r\n" + "    \"home_league_GA\": \"26\",\r\n"
			+ "    \"home_league_PTS\": \"15\",\r\n" + "    \"away_league_position\": \"14\",\r\n"
			+ "    \"away_promotion\": \"\",\r\n" + "    \"away_league_payed\": \"15\",\r\n"
			+ "    \"away_league_W\": \"3\",\r\n" + "    \"away_league_D\": \"3\",\r\n"
			+ "    \"away_league_L\": \"9\",\r\n" + "    \"away_league_GF\": \"12\",\r\n"
			+ "    \"away_league_GA\": \"24\",\r\n" + "    \"away_league_PTS\": \"12\",\r\n"
			+ "    \"league_round\": \"\",\r\n"
			+ "    \"team_badge\": \"https:\\/\\/apiv2.apifootball.com\\/badges\\/2620_west-ham.png\"\r\n" + "  },\r\n"
			+ "  {\r\n" + "    \"country_name\": \"England\",\r\n" + "    \"league_id\": \"148\",\r\n"
			+ "    \"league_name\": \"Premier League\",\r\n" + "    \"team_id\": \"2623\",\r\n"
			+ "    \"team_name\": \"Watford\",\r\n" + "    \"overall_promotion\": \"\",\r\n"
			+ "    \"overall_league_position\": \"17\",\r\n" + "    \"overall_league_payed\": \"29\",\r\n"
			+ "    \"overall_league_W\": \"6\",\r\n" + "    \"overall_league_D\": \"9\",\r\n"
			+ "    \"overall_league_L\": \"14\",\r\n" + "    \"overall_league_GF\": \"27\",\r\n"
			+ "    \"overall_league_GA\": \"44\",\r\n" + "    \"overall_league_PTS\": \"27\",\r\n"
			+ "    \"home_league_position\": \"15\",\r\n" + "    \"home_promotion\": \"\",\r\n"
			+ "    \"home_league_payed\": \"14\",\r\n" + "    \"home_league_W\": \"4\",\r\n"
			+ "    \"home_league_D\": \"5\",\r\n" + "    \"home_league_L\": \"5\",\r\n"
			+ "    \"home_league_GF\": \"16\",\r\n" + "    \"home_league_GA\": \"17\",\r\n"
			+ "    \"home_league_PTS\": \"17\",\r\n" + "    \"away_league_position\": \"18\",\r\n"
			+ "    \"away_promotion\": \"\",\r\n" + "    \"away_league_payed\": \"15\",\r\n"
			+ "    \"away_league_W\": \"2\",\r\n" + "    \"away_league_D\": \"4\",\r\n"
			+ "    \"away_league_L\": \"9\",\r\n" + "    \"away_league_GF\": \"11\",\r\n"
			+ "    \"away_league_GA\": \"27\",\r\n" + "    \"away_league_PTS\": \"10\",\r\n"
			+ "    \"league_round\": \"\",\r\n"
			+ "    \"team_badge\": \"https:\\/\\/apiv2.apifootball.com\\/badges\\/2623_watford.png\"\r\n" + "  },\r\n"
			+ "  {\r\n" + "    \"country_name\": \"England\",\r\n" + "    \"league_id\": \"148\",\r\n"
			+ "    \"league_name\": \"Premier League\",\r\n" + "    \"team_id\": \"2615\",\r\n"
			+ "    \"team_name\": \"Bournemouth\",\r\n"
			+ "    \"overall_promotion\": \"Relegation - Championship\",\r\n"
			+ "    \"overall_league_position\": \"18\",\r\n" + "    \"overall_league_payed\": \"29\",\r\n"
			+ "    \"overall_league_W\": \"7\",\r\n" + "    \"overall_league_D\": \"6\",\r\n"
			+ "    \"overall_league_L\": \"16\",\r\n" + "    \"overall_league_GF\": \"29\",\r\n"
			+ "    \"overall_league_GA\": \"47\",\r\n" + "    \"overall_league_PTS\": \"27\",\r\n"
			+ "    \"home_league_position\": \"16\",\r\n" + "    \"home_promotion\": \"\",\r\n"
			+ "    \"home_league_payed\": \"14\",\r\n" + "    \"home_league_W\": \"4\",\r\n"
			+ "    \"home_league_D\": \"5\",\r\n" + "    \"home_league_L\": \"5\",\r\n"
			+ "    \"home_league_GF\": \"17\",\r\n" + "    \"home_league_GA\": \"21\",\r\n"
			+ "    \"home_league_PTS\": \"17\",\r\n" + "    \"away_league_position\": \"17\",\r\n"
			+ "    \"away_promotion\": \"\",\r\n" + "    \"away_league_payed\": \"15\",\r\n"
			+ "    \"away_league_W\": \"3\",\r\n" + "    \"away_league_D\": \"1\",\r\n"
			+ "    \"away_league_L\": \"11\",\r\n" + "    \"away_league_GF\": \"12\",\r\n"
			+ "    \"away_league_GA\": \"26\",\r\n" + "    \"away_league_PTS\": \"10\",\r\n"
			+ "    \"league_round\": \"\",\r\n"
			+ "    \"team_badge\": \"https:\\/\\/apiv2.apifootball.com\\/badges\\/2615_bournemouth.png\"\r\n"
			+ "  },\r\n" + "  {\r\n" + "    \"country_name\": \"England\",\r\n" + "    \"league_id\": \"148\",\r\n"
			+ "    \"league_name\": \"Premier League\",\r\n" + "    \"team_id\": \"2632\",\r\n"
			+ "    \"team_name\": \"Aston Villa\",\r\n"
			+ "    \"overall_promotion\": \"Relegation - Championship\",\r\n"
			+ "    \"overall_league_position\": \"19\",\r\n" + "    \"overall_league_payed\": \"28\",\r\n"
			+ "    \"overall_league_W\": \"7\",\r\n" + "    \"overall_league_D\": \"4\",\r\n"
			+ "    \"overall_league_L\": \"17\",\r\n" + "    \"overall_league_GF\": \"34\",\r\n"
			+ "    \"overall_league_GA\": \"56\",\r\n" + "    \"overall_league_PTS\": \"25\",\r\n"
			+ "    \"home_league_position\": \"17\",\r\n" + "    \"home_promotion\": \"\",\r\n"
			+ "    \"home_league_payed\": \"13\",\r\n" + "    \"home_league_W\": \"5\",\r\n"
			+ "    \"home_league_D\": \"2\",\r\n" + "    \"home_league_L\": \"6\",\r\n"
			+ "    \"home_league_GF\": \"18\",\r\n" + "    \"home_league_GA\": \"24\",\r\n"
			+ "    \"home_league_PTS\": \"17\",\r\n" + "    \"away_league_position\": \"19\",\r\n"
			+ "    \"away_promotion\": \"\",\r\n" + "    \"away_league_payed\": \"15\",\r\n"
			+ "    \"away_league_W\": \"2\",\r\n" + "    \"away_league_D\": \"2\",\r\n"
			+ "    \"away_league_L\": \"11\",\r\n" + "    \"away_league_GF\": \"16\",\r\n"
			+ "    \"away_league_GA\": \"32\",\r\n" + "    \"away_league_PTS\": \"8\",\r\n"
			+ "    \"league_round\": \"\",\r\n"
			+ "    \"team_badge\": \"https:\\/\\/apiv2.apifootball.com\\/badges\\/2632_aston-villa.png\"\r\n"
			+ "  },\r\n" + "  {\r\n" + "    \"country_name\": \"England\",\r\n" + "    \"league_id\": \"148\",\r\n"
			+ "    \"league_name\": \"Premier League\",\r\n" + "    \"team_id\": \"2641\",\r\n"
			+ "    \"team_name\": \"Norwich\",\r\n" + "    \"overall_promotion\": \"Relegation - Championship\",\r\n"
			+ "    \"overall_league_position\": \"20\",\r\n" + "    \"overall_league_payed\": \"29\",\r\n"
			+ "    \"overall_league_W\": \"5\",\r\n" + "    \"overall_league_D\": \"6\",\r\n"
			+ "    \"overall_league_L\": \"18\",\r\n" + "    \"overall_league_GF\": \"25\",\r\n"
			+ "    \"overall_league_GA\": \"52\",\r\n" + "    \"overall_league_PTS\": \"21\",\r\n"
			+ "    \"home_league_position\": \"19\",\r\n" + "    \"home_promotion\": \"\",\r\n"
			+ "    \"home_league_payed\": \"14\",\r\n" + "    \"home_league_W\": \"4\",\r\n"
			+ "    \"home_league_D\": \"3\",\r\n" + "    \"home_league_L\": \"7\",\r\n"
			+ "    \"home_league_GF\": \"19\",\r\n" + "    \"home_league_GA\": \"26\",\r\n"
			+ "    \"home_league_PTS\": \"15\",\r\n" + "    \"away_league_position\": \"20\",\r\n"
			+ "    \"away_promotion\": \"\",\r\n" + "    \"away_league_payed\": \"15\",\r\n"
			+ "    \"away_league_W\": \"1\",\r\n" + "    \"away_league_D\": \"3\",\r\n"
			+ "    \"away_league_L\": \"11\",\r\n" + "    \"away_league_GF\": \"6\",\r\n"
			+ "    \"away_league_GA\": \"26\",\r\n" + "    \"away_league_PTS\": \"6\",\r\n"
			+ "    \"league_round\": \"\",\r\n"
			+ "    \"team_badge\": \"https:\\/\\/apiv2.apifootball.com\\/badges\\/2641_norwich.png\"\r\n" + "  }\r\n"
			+ "]";

	@Before
	public void setup() {
		mockMvc = MockMvcBuilders.standaloneSetup(controller).build();
		MockitoAnnotations.initMocks(this);
	}

	@Test
	public void testStandings404() throws Exception {
		MockHttpServletRequestBuilder builder = MockMvcRequestBuilders.get("/standings)");
		Mockito.when(service.teamStandings("standings", "148", "testKey")).thenReturn(response);
		ResultMatcher matcher = MockMvcResultMatchers.status().isNotFound();
		this.mockMvc.perform(builder).andDo(MockMvcResultHandlers.print()).andExpect(matcher);
	}

	@Test
	public void testStandings() throws Exception {
		MockHttpServletRequestBuilder builder = MockMvcRequestBuilders.get(
				"/standings?action=get_standings&league_id=148&APIkey=9bb66184e0c8145384fd2cc0f7b914ada57b4e8fd2e4d6d586adcc27c257a978)");
		Mockito.when(service.teamStandings("get_standings", "148",
				"9bb66184e0c8145384fd2cc0f7b914ada57b4e8fd2e4d6d586adcc27c257a978")).thenReturn(response);
		ResultMatcher matcher = MockMvcResultMatchers.status().isOk();
		this.mockMvc.perform(builder).andDo(MockMvcResultHandlers.print()).andExpect(matcher);
	}

}
